### ISSUE TITLE
Failed to obtain access token

### ISSUE THREAD

**Issue by fundon** [jaredhanson/passport-facebook#116]
```js
  app.get('/auth/facebook', passport.authenticate('facebook'));

  app.get('/auth/facebook/callback',
    passport.authenticate('facebook', {
      failureRedirect: '/login'
    }),
    function(req, res) {
      res.cookie('signIn', 'true');
      res.redirect('/');
    }
  );
```

```
InternalOAuthError: Failed to obtain access token
   at Strategy.OAuth2Strategy._createOAuthError (/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:348:17)
   at /node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:171:43
   at /node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
   at ClientRequest.<anonymous> (/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:148:5)
   at emitOne (events.js:77:13)
   at ClientRequest.emit (events.js:166:7)
   at TLSSocket.socketErrorListener (_http_client.js:255:9)
   at emitOne (events.js:77:13)
   at TLSSocket.emit (events.js:166:7)
   at net.js:438:14
```

**Comment by fundon** [comment]
I thought that is networking problem.

**Comment by theJian** [comment]
I have the same issue, could you please tell me how you solve it?

**Comment by Jasguerrero** [comment]
So did you found a solution? I have the same problem

**Comment by theJian** [comment]
Have you checked your network? That is, could you connect to facebook on your host?

**Comment by usama-nayab** [comment]
having the same problem.. anybody found solution?
