### ISSUE TITLE
Doesn't work without successRedirect

### ISSUE THREAD

**Issue by akuz** [jaredhanson/passport-facebook#118]
I am trying to implement a custom functionality after successful login, but the strategy fails if I don't provide the successRedirect parameter. My code:

    router.get (
        '/signin/facebook',
        passport.authenticate ('facebook', { session: false }));

    router.get (
        '/signin/facebook/callback', 
        function (res, req, next) {

            // override default passport behaviour
            passport.authenticate (providerName, function (err, user, info) {

                if (err) {
                    return next (err);
                }

                if (user) {

                    // TODO: logged in
                    res.send("Logged in");

                } else {

                    // TODO: not logged in
                    res.send("Access denied");
                }

            }) (req, res, next);

        });

Which produces error from within passport-facebook attempting to redirect:

TypeError: undefined is not a function
   at Strategy.strategy.redirect (/REMOVED/node_modules/passport/lib/middleware/authenticate.js:303:13)
   at Strategy.OAuth2Strategy.authenticate (/REMOVED/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:227:10)
   at Strategy.authenticate (/REMOVED/node_modules/passport-facebook/lib/strategy.js:85:41)
   at attempt (/node_modules/passport/lib/middleware/authenticate.js:341:16)
   at authenticate (/REMOVED/node_modules/passport/lib/middleware/authenticate.js:342:7)

**Comment by akuz** [comment]
The following code works:

router.get (
    '/signin/facebook',
    passport.authenticate ('facebook', { session: false }));

router.get (
    '/signin/facebook/callback', 
    passport.authenticate ('facebook', { session: false }),
    function (res, req, next) {

        if (req.user) {

            // TODO: logged in
            res.send("Logged in");

        } else {

            // TODO: not logged in
            res.send("Access denied");
        }
    });
