### ISSUE TITLE
error when send access_token for other APP_ID 

### ISSUE THREAD

**Issue by Vilintritenmert** [jaredhanson/passport-facebook#196]
crash) when send access_token for other APP_ID

**Comment by Vilintritenmert** [comment]
Error
<br> &nbsp; &nbsp;at C:\OpenServer\domains\kafe.loc\node_modules\passport-facebook-token\lib\index.js:155:32
<br> &nbsp; &nbsp;at passBackControl (C:\OpenServer\domains\kafe.loc\node_modules\oauth\lib\oauth2.js:123:9)
<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (C:\OpenServer\domains\kafe.loc\node_modules\oauth\lib\oauth2.js:143:7)
<br> &nbsp; &nbsp;at emitNone (events.js:91:20)
<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)
<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)
<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:74:11)
<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Joshuabaker2** [comment]
This is most likely because you haven't whitelisted your ip address for your facebook app. 

Within your app settings in your facebook developer account, go to the advanced settings, and put your server's external IP address in the whitelist.
