### ISSUE TITLE
Earlier i'm able to authenticate , now it showing me error 

### ISSUE THREAD

**Issue by pankajnarwal11** [jaredhanson/passport-facebook#216]
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/home/pankaj/work/expressjs_project/oauth2check/node_modules/passport-oauth2/lib/strategy.js:379:17)
    at /home/pankaj/work/expressjs_project/oauth2check/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /home/pankaj/work/expressjs_project/oauth2check/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/home/pankaj/work/expressjs_project/oauth2check/node_modules/oauth/lib/oauth2.js:162:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)

**Comment by angelxmoreno** [comment]
@pankajnarwal11 shouldn't this be under `passport-google-oauth20` instead of `passport-facebook` ?
