### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by tarakeshp** [jaredhanson/passport-facebook#245]
Hi,
I have nodejs application with proxied from nginx webserver. Though the callback executes from facebook and responds as 302, for some reason, the cookies are getting vanished and lands at login page again..
I am completely confused.
The same application is deployed cloudjiffy.net with openresty/1.13.6.1 and every thing works normally.

Nginx Configuration

server {
        listen 80;
        listen 443 ssl;

        server_name  oidc.icrypto.com;
        root         /usr/share/nginx/html;

 #       ssl on;
        ssl_certificate /etc/nginx/ssl/star_icrypto_com.pem;
        ssl_certificate_key /etc/nginx/ssl/star_icrypto_com.key;
        ssl_prefer_server_ciphers on;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
                proxy_pass http://localhost:9000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header X-NginX-Proxy true;
                proxy_buffers 16 4k;
                proxy_buffer_size 2k;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }

https://oidc.icrypto.com/login - not working
http://node5032-env-9682770.cloudjiffy.net - works

Thanks in advance

**Comment by tarakeshp** [comment]
{ clientID: process.env.FACEBOOK_ID,
  clientSecret: process.env.FACEBOOK_SECRET,
  **callbackURL: "https://oidc.icrypto.com/auth/facebook/callback",**
  profileFields: ["name", "email", "link", "locale", "timezone"], }

redirect to login again


{
clientID: process.env.FACEBOOK_ID,
  clientSecret: process.env.FACEBOOK_SECRET,
  **callbackURL: "/auth/facebook/callback",**
  profileFields: ["name", "email", "link", "locale", "timezone"],
  passReqToCallback: true,
  enableProof: false

}

getting error
Connect
500 FacebookTokenError: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.
   at Strategy.parseErrorResponse (/home/icrypto/passport/node_modules/passport-facebook/lib/strategy.js:196:12)
   at Strategy.OAuth2Strategy._createOAuthError (/home/icrypto/passport/node_modules/passport-oauth2/lib/strategy.js:376:16)
   at /home/icrypto/passport/node_modules/passport-oauth2/lib/strategy.js:166:45
   at /home/icrypto/passport/node_modules/oauth/lib/oauth2.js:191:18
   at passBackControl (/home/icrypto/passport/node_modules/oauth/lib/oauth2.js:132:9)
   at IncomingMessage.<anonymous> (/home/icrypto/passport/node_modules/oauth/lib/oauth2.js:157:7)
   at IncomingMessage.emit (events.js:164:20)
   at endReadableNT (_stream_readable.js:1054:12)
   at _combinedTickCallback (internal/process/next_tick.js:138:11)
   at process._tickDomainCallback (internal/process/next_tick.js:218:9)
