### ISSUE TITLE
User is not defined

### ISSUE THREAD

**Issue by joy2323** [jaredhanson/passport-facebook#257]
ReferenceError: User is not defined
    at Strategy._verify (C:\Users\JAY JAY\Documents\remote_job_alert\app.js:124:5)
    at C:\Users\JAY JAY\Documents\remote_job_alert\node_modules\passport-oauth2\lib\strategy.js:202:24
    at C:\Users\JAY JAY\Documents\remote_job_alert\node_modules\passport-facebook\lib\strategy.js:183:5
    at passBackControl (C:\Users\JAY JAY\Documents\remote_job_alert\node_modules\oauth\lib\oauth2.js:134:9)
    at IncomingMessage.<anonymous> (C:\Users\JAY JAY\Documents\remote_job_alert\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

i got the above error after clicking on "continue as Joy"

**Comment by kuldeepsharma8** [comment]
You haven't declare your User.js file. please declare your User.js file, hope this will helps you
