### ISSUE TITLE
FacebookToken Error via localhost

### ISSUE THREAD

**Issue by lcy101u** [jaredhanson/passport-facebook#288]
### facebook strategy
```
passport.use(new FacebookStrategy({
    clientID: process.env.FACEBOOK_ID,
    clientSecret: process.env.FACEBOOK_SECRET,
    callbackURL: process.env.FACEBOOK_CALLBACK,
    profileFields: ['email', 'displayName']
  }, (accessToken, refreshToken, profile, done) => {
    console.log(profile)
    //.....
  }))
```
### authenticate
```
router.get('/facebook', (req, res, next) => {
  console.log('FB authentication !!!!')
  next()
},passport.authenticate('facebook', {
  scope: ['email', 'public_profile']
}))

router.get('/facebook/callback',(req, res, next) => {
  console.log('FB callback!!!!')
  next()
},  passport.authenticate('facebook', {
  successRedirect: '/',
  failureRedirect: '/users/login',
}))
```
### This is what I got
Listening on http://localhost:3000
mongodb connected!
FB authentication !!!!
FB callback!!!!
FacebookTokenError: Can't Load URL: The domain of this URL isn't included in the app's domains
    at Strategy.parseErrorResponse (D:\_Projects\todo-list\node_modules\passport-facebook\lib\strategy.js:198:12)
    at Strategy.OAuth2Strategy._createOAuthError (D:\_Projects\todo-list\node_modules\passport-oauth2\lib\strategy.js:420:16)
    at D:\_Projects\todo-list\node_modules\passport-oauth2\lib\strategy.js:177:45
    at D:\_Projects\todo-list\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (D:\_Projects\todo-list\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (D:\_Projects\todo-list\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

### What I had tried
[Stackoverflow
](https://stackoverflow.com/questions/60819498/facebooktokenerror-cant-load-url-the-domain-of-this-url-isnt-included-in-the)
But since I use localhsot, so I left "Valid OAuth Redirect URIs" empty

### Environment

* Operating System: Window 10 
* Node version: v14.16.0
* passport version: 0.5.2
* passport-facebook version: 3.0.0

**Comment by blender222** [comment]
I have same problem when running in localhost.
(FacebookTokenError: Can't Load URL: The domain of this URL isn't included in the app's domains)

but it works when deploy to heroku

**Comment by lcy101u** [comment]
@blender222 Looks like it is a bug from Meta (Facebook), I tried again in localhost and it works fine now.
